# This file was generated by GoReleaser. DO NOT EDIT.
cask "toolsniff" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "4c13b6b340d584662e65f8e31ad803b61e49eb5e3f8b5bf2b14b69332803363a"
      url "https://github.com/pranvgarg/toolsniff/releases/download/v#{version}/toolsniff_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "26a548af0207ce7b4c04849c8e645856a44715024e02bc059dfc4939554430a3"
      url "https://github.com/pranvgarg/toolsniff/releases/download/v#{version}/toolsniff_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "toolsniff"
  desc "Discover installed developer and AI tools on macOS"
  homepage "https://github.com/pranvgarg/toolsniff"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toolsniff"

  # No zap stanza required

end
