# This file was generated by GoReleaser. DO NOT EDIT.
cask "toolsniff" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "de5b73769315a31a3a0bb138d912da31ac672b960700d7590c390470365424bc"
      url "https://github.com/pranvgarg/toolsniff/releases/download/v#{version}/toolsniff_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e668b40e690545b30a104020ec69e431709cbc03b448c0bf745cdfa5fa643c7a"
      url "https://github.com/pranvgarg/toolsniff/releases/download/v#{version}/toolsniff_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "toolsniff"
  desc "Discover installed developer and AI tools on macOS"
  homepage "https://github.com/pranvgarg/toolsniff"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toolsniff"

  # No zap stanza required
end
