# This file was generated by GoReleaser. DO NOT EDIT.
cask "toolsniff" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "60e54402d3a25a265fc8e043a340b02fc0bb3c65e5fe589e2aa1c4f30bec0deb"
      url "https://github.com/pranvgarg/toolsniff/releases/download/v#{version}/toolsniff_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b0b761bb351d6a6e1c8cecf6a1f0cba7ed2401528dfa0a80360db36563edf6da"
      url "https://github.com/pranvgarg/toolsniff/releases/download/v#{version}/toolsniff_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "toolsniff"
  desc "Discover installed developer and AI tools on macOS"
  homepage "https://github.com/pranvgarg/toolsniff"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toolsniff"

  # No zap stanza required

end
