# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toolsniff < Formula
  desc "Discover installed developer and AI tools on macOS"
  homepage "https://github.com/pranvgarg/toolsniff"
  version "0.2.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/pranvgarg/toolsniff/releases/download/v0.2.0/toolsniff_0.2.0_darwin_amd64.tar.gz"
    sha256 "e668b40e690545b30a104020ec69e431709cbc03b448c0bf745cdfa5fa643c7a"

    define_method(:install) do
      bin.install "toolsniff"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/pranvgarg/toolsniff/releases/download/v0.2.0/toolsniff_0.2.0_darwin_arm64.tar.gz"
    sha256 "de5b73769315a31a3a0bb138d912da31ac672b960700d7590c390470365424bc"

    define_method(:install) do
      bin.install "toolsniff"
    end
  end

  test do
    system "#{bin}/toolsniff", "--version"
  end
end
